window.EMBEDDED_BASELINES = [
  {
    "id": "baseline-it",
    "name": "Baseline - Generell IT-tjeneste",
    "metadata": {
      "tjeneste": "Baseline - Generell IT-tjeneste",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for generelle IT-tjenester. Bruk som utgangspunkt og tilpass til din spesifikke tjeneste.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-it-001",
        "risikoelement": "Bruker beholder tilgang etter at bruker har sluttet/endret stilling",
        "saarbarhet": "Dårlige rutiner for avslutning av brukere, manglende automatikk",
        "eksisterendeBeskyttelse": "Delvis HR-system integrasjon",
        "eksisterendeKontroll": "Kvartalsvis tilgangsgjennomgang",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Automatisk deaktivering ved avslutning, full integrasjon med HR-system",
        "kommentarer": []
      },
      {
        "id": "baseline-it-002",
        "risikoelement": "Uvedkommende får tilgang pga. passord på avveie",
        "saarbarhet": "Usikker oppbevaring av passord, passord som brukes på flere systemer",
        "eksisterendeBeskyttelse": "Passordpolicy med krav til kompleksitet",
        "eksisterendeKontroll": "Tofaktorautentisering for admin",
        "K": 5,
        "I": 4,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "Passkeys/FIDO2, obligatorisk tofaktor for alle",
        "kommentarer": []
      },
      {
        "id": "baseline-it-003",
        "risikoelement": "Manglende eller utdatert sårbarhetshåndtering",
        "saarbarhet": "Kjente sårbarheter ikke patchet i tide, manglende oversikt over systemer",
        "eksisterendeBeskyttelse": "Månedlig patching-vindu",
        "eksisterendeKontroll": "Manuell sjekk av tilgjengelige oppdateringer",
        "K": 5,
        "I": 4,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Automatisert vulnerability scanning, asset inventory, risikobasert prioritering av patching",
        "kommentarer": []
      },
      {
        "id": "baseline-it-004",
        "risikoelement": "Utilstrekkelig logging og manglende deteksjon",
        "saarbarhet": "Sikkerhetshendelser logges ikke eller oppdages for sent",
        "eksisterendeBeskyttelse": "Basic logging til lokale filer",
        "eksisterendeKontroll": "Manuell gjennomgang ved mistanke",
        "K": 4,
        "I": 4,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Sentralisert logging (SIEM), definere use cases for alerts, log retention policy",
        "kommentarer": []
      },
      {
        "id": "baseline-it-005",
        "risikoelement": "Manglende backup eller backup ikke testet",
        "saarbarhet": "Data går tapt ved feil eller angrep, backup feiler uten varsling",
        "eksisterendeBeskyttelse": "Automatiserte backup-jobber",
        "eksisterendeKontroll": "Ukentlig manuell sjekk av logger",
        "K": 5,
        "I": 5,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "Implementere 3-2-1 backup-strategi, kvartalsvis restore-test, automatisk monitorering av backup-status",
        "kommentarer": []
      },
      {
        "id": "baseline-it-006",
        "risikoelement": "SQL injection eller andre injection-angrep",
        "saarbarhet": "Manglende input validering, direkte bruk av brukerinput i queries",
        "eksisterendeBeskyttelse": "Noe input validering",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 5,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Parameteriserte queries, ORM-bruk, input validering, SAST/DAST scanning",
        "kommentarer": []
      },
      {
        "id": "baseline-it-007",
        "risikoelement": "Ukryptert kommunikasjon",
        "saarbarhet": "Data overføres i klartekst, MITM-angrep mulig",
        "eksisterendeBeskyttelse": "HTTPS på eksterne endepunkter",
        "eksisterendeKontroll": "SSL-sertifikater på web",
        "K": 4,
        "I": 3,
        "T": 1,
        "konsekvens": 4,
        "sannsynlighet": 2,
        "risikonivaa": 8,
        "foreslaatteTiltak": "TLS 1.3 for all kommunikasjon (intern og ekstern), HSTS, sertifikat pinning der relevant",
        "kommentarer": []
      },
      {
        "id": "baseline-it-008",
        "risikoelement": "Manglende eller utilstrekkelig BCP/DR-plan",
        "saarbarhet": "Ingen plan for gjenoppretting ved katastrofe, ukjent RTO/RPO",
        "eksisterendeBeskyttelse": "Ad-hoc krisehåndtering",
        "eksisterendeKontroll": "Ingen formell plan",
        "K": 5,
        "I": 3,
        "T": 5,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Utarbeide formell BCP/DR-plan, definere RTO/RPO, årlig test av plan",
        "kommentarer": []
      },
      {
        "id": "baseline-it-009",
        "risikoelement": "Utilstrekkelig security awareness hos ansatte",
        "saarbarhet": "Ansatte klikker på phishing, deler passord, ikke-rapporterer sikkerhetshendelser",
        "eksisterendeBeskyttelse": "Onboarding-intro til sikkerhet",
        "eksisterendeKontroll": "Sporadiske e-poster om sikkerhet",
        "K": 4,
        "I": 3,
        "T": 3,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Årlig obligatorisk security awareness training, månedlige phishing-simuleringer, sikkerhetskultur",
        "kommentarer": []
      },
      {
        "id": "baseline-it-010",
        "risikoelement": "Secrets og API-nøkler i kode eller config",
        "saarbarhet": "Hardkodede passord, nøkler i git, ingen rotasjon",
        "eksisterendeBeskyttelse": ".gitignore for secrets",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 3,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Secrets management (Vault, Key Vault), secret scanning i CI/CD, rotasjonspolicy",
        "kommentarer": []
      }
    ]
  },
  {
    "id": "baseline-sky",
    "name": "Baseline - Skytjeneste (AWS/Azure/GCP)",
    "metadata": {
      "tjeneste": "Baseline - Skytjeneste (AWS/Azure/GCP)",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for skytjenester (AWS, Azure, GCP). Bruk som utgangspunkt og tilpass til din spesifikke skyløsning.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-sky-001",
        "risikoelement": "Feilkonfigurert IAM gir for vide tilganger",
        "saarbarhet": "Over-privilegerte roller, manglende least privilege, wildcards i policies",
        "eksisterendeBeskyttelse": "IAM roles brukes",
        "eksisterendeKontroll": "Manuell gjennomgang ved opprettelse",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "IAM Access Analyzer, least privilege reviews, policy conditions, remove wildcards",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-002",
        "risikoelement": "Offentlig eksponerte S3 buckets / storage accounts",
        "saarbarhet": "Utilsiktet public access på storage med sensitiv data",
        "eksisterendeBeskyttelse": "Noen buckets har access control",
        "eksisterendeKontroll": "Sporadisk manuell sjekk",
        "K": 5,
        "I": 5,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Block public access default, automated scanning for public buckets, bucket policies enforcement",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-003",
        "risikoelement": "Manglende kryptering av data at rest",
        "saarbarhet": "Data lagret ukryptert i sky, kan leses ved brudd",
        "eksisterendeBeskyttelse": "Kryptering på noen kritiske databaser",
        "eksisterendeKontroll": "Manuell konfigurasjon",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "Enforce encryption at rest for all storage (S3, EBS, RDS, etc.), KMS/Key Vault for key management",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-004",
        "risikoelement": "Ukryptert trafikk i VPC/VNet",
        "saarbarhet": "Intern trafikk i klartekst, lateral movement lettere ved kompromittering",
        "eksisterendeBeskyttelse": "HTTPS for ekstern trafikk",
        "eksisterendeKontroll": "TLS på API gateways",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 2,
        "risikonivaa": 8,
        "foreslaatteTiltak": "Service mesh med mTLS (Istio, Linkerd), VPN for admin-tilgang, private endpoints",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-005",
        "risikoelement": "Manglende logging og monitoring i skymiljø",
        "saarbarhet": "CloudTrail/Activity Log ikke aktivert eller logges ikke sentralt",
        "eksisterendeBeskyttelse": "Basic CloudWatch metrics",
        "eksisterendeKontroll": "Dashboard for noen metrics",
        "K": 4,
        "I": 4,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Enable CloudTrail/Activity Log for all regions, centralized logging, SIEM integration, GuardDuty/Security Center",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-006",
        "risikoelement": "Utilstrekkelig network segmentering",
        "saarbarhet": "Flat network, alle ressurser kan kommunisere, manglende security groups/NSGs",
        "eksisterendeBeskyttelse": "VPC/VNet opprettet",
        "eksisterendeKontroll": "Noen security groups",
        "K": 4,
        "I": 3,
        "T": 3,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Multi-tier architecture (public/private/data subnets), strict security groups, NACLs, microsegmentation",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-007",
        "risikoelement": "Manglende tagging og cost control",
        "saarbarhet": "Ukontrollerte kostnader, vanskelig å spore ressurseierskap, zombie resources",
        "eksisterendeBeskyttelse": "Noen tags på kritiske ressurser",
        "eksisterendeKontroll": "Månedlig billing review",
        "K": 2,
        "I": 1,
        "T": 1,
        "konsekvens": 2,
        "sannsynlighet": 4,
        "risikonivaa": 8,
        "foreslaatteTiltak": "Mandatory tagging policy (owner, environment, cost-center), budgets with alerts, automated cleanup of unused resources",
        "kommentarer": []
      },
      {
        "id": "baseline-sky-008",
        "risikoelement": "Credential leakage i EC2/VM metadata service",
        "saarbarhet": "IMDSv1 tillater SSRF-angrep for å stjele credentials",
        "eksisterendeBeskyttelse": "Standard IMDS konfigurasjon",
        "eksisterendeKontroll": "Ingen spesifikk hardening",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "Enforce IMDSv2 (session tokens), disable metadata service der ikke nødvendig",
        "kommentarer": []
      }
    ]
  },
  {
    "id": "baseline-persondata",
    "name": "Baseline - Persondata/GDPR",
    "metadata": {
      "tjeneste": "Baseline - Persondata/GDPR",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for tjenester som behandler personopplysninger. Bruk som utgangspunkt for GDPR-compliance.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-pd-001",
        "risikoelement": "Manglende eller ugyldig behandlingsgrunnlag",
        "saarbarhet": "Behandler personopplysninger uten gyldig rettslig grunnlag (Art. 6 GDPR)",
        "eksisterendeBeskyttelse": "Samtykke innhentes",
        "eksisterendeKontroll": "Vurdering ved implementasjon",
        "K": 5,
        "I": 3,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Dokumentere behandlingsgrunnlag for alle behandlinger, vurdere legitimt grunnlag vs samtykke, juridisk review",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-002",
        "risikoelement": "Utilstrekkelig informasjon til registrerte",
        "saarbarhet": "Personvernerklæring mangler eller er ufullstendig (Art. 13/14 GDPR)",
        "eksisterendeBeskyttelse": "Generell personvernerklæring",
        "eksisterendeKontroll": "Publisert på nettsiden",
        "K": 3,
        "I": 2,
        "T": 2,
        "konsekvens": 3,
        "sannsynlighet": 3,
        "risikonivaa": 9,
        "foreslaatteTiltak": "Oppdatere personvernerklæring med alle GDPR-krav, klart språk, lett tilgjengelig",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-003",
        "risikoelement": "Manglende håndtering av registrertes rettigheter",
        "saarbarhet": "Ingen prosess for innsyn, sletting, portabilitet, korrigering (Art. 15-20 GDPR)",
        "eksisterendeBeskyttelse": "E-post til support",
        "eksisterendeKontroll": "Ad-hoc håndtering",
        "K": 4,
        "I": 3,
        "T": 3,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Etablere formelle prosedyrer for alle rettigheter, SLA (1 måned), logging, self-service der mulig",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-004",
        "risikoelement": "Personopplysninger beholdes for lenge",
        "saarbarhet": "Ingen sletterutiner, data aldri slettet, brudd på lagringsbegrensning (Art. 5)",
        "eksisterendeBeskyttelse": "Ingen automatisk sletting",
        "eksisterendeKontroll": "Manuell sletting ved forespørsel",
        "K": 3,
        "I": 2,
        "T": 3,
        "konsekvens": 3,
        "sannsynlighet": 5,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Definere lagringsperioder per formål, automatisk sletting, logging av sletting",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-005",
        "risikoelement": "Databehandleravtaler mangler eller er mangelfulle",
        "saarbarhet": "Leverandører behandler personopplysninger uten DBA (Art. 28 GDPR)",
        "eksisterendeBeskyttelse": "Standard leverandøravtaler",
        "eksisterendeKontroll": "Ikke systematisk DBA-inngåelse",
        "K": 4,
        "I": 3,
        "T": 3,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Kartlegge alle databehandlere, inngå DBA med GDPR Art. 28-krav, supplier assessment",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-006",
        "risikoelement": "Overføring til tredjeland uten sikkerhetstiltak",
        "saarbarhet": "Personopplysninger overføres utenfor EU/EØS uten adekvat beskyttelse (Art. 44-50)",
        "eksisterendeBeskyttelse": "Noen leverandører er Privacy Shield",
        "eksisterendeKontroll": "Ikke systematisk vurdering",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Kartlegge alle tredjelandsoverføringer, SCCs, adequacy decisions, TIA vurdering",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-007",
        "risikoelement": "Manglende DPIA for høyrisiko behandling",
        "saarbarhet": "Ingen personvernkonsekvensvurdering for behandlinger som innebærer høy risiko (Art. 35)",
        "eksisterendeBeskyttelse": "ROS-analyse utført",
        "eksisterendeKontroll": "Ikke DPIA-spesifikk",
        "K": 4,
        "I": 3,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Gjennomføre DPIA for høyrisiko behandlinger (profilering, automatiserte beslutninger, storskala sensitiv data)",
        "kommentarer": []
      },
      {
        "id": "baseline-pd-008",
        "risikoelement": "Personvernbrudd ikke rapportert",
        "saarbarhet": "Ingen prosess for deteksjon og rapportering av personvernbrudd (Art. 33/34)",
        "eksisterendeBeskyttelse": "Incident response prosedyre",
        "eksisterendeKontroll": "Ikke personvernspesifikk",
        "K": 5,
        "I": 4,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "Etablere breach notification prosedyre (72-timer til Datatilsynet), varsling til registrerte, breach register",
        "kommentarer": []
      }
    ]
  },
  {
    "id": "baseline-webapp",
    "name": "Baseline - Webapp/API",
    "metadata": {
      "tjeneste": "Baseline - Webapp/API",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for webapplikasjoner og API-er. OWASP Top 10 og API-sikkerhet.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-webapp-001",
        "risikoelement": "Brutte tilgangskontroller (Broken Access Control)",
        "saarbarhet": "Manglende autorisasjonssjekker, IDOR, path traversal, privilege escalation",
        "eksisterendeBeskyttelse": "Påloggingskrav",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 5,
        "risikonivaa": 25,
        "foreslaatteTiltak": "Deny by default, konsistent autorisasjon på server-side, unit tests for authz, ABAC/RBAC",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-002",
        "risikoelement": "Kryptografiske svakheter",
        "saarbarhet": "Svake algoritmer, hardkodede nøkler, usikker random, manglende salting",
        "eksisterendeBeskyttelse": "HTTPS",
        "eksisterendeKontroll": "Standard biblioteker",
        "K": 5,
        "I": 4,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Moderne algoritmer (AES-256, RSA-2048+), secrets manager, bcrypt/argon2 for passord, crypto review",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-003",
        "risikoelement": "Injection-angrep (SQL, NoSQL, LDAP, OS)",
        "saarbarhet": "Manglende input validering, direkte bruk av brukerinput i queries/kommandoer",
        "eksisterendeBeskyttelse": "Noe input sanitering",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 5,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "Parameteriserte queries, ORM, input validering, least privilege DB-brukere, SAST",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-004",
        "risikoelement": "Insikker design (manglende threat modeling)",
        "saarbarhet": "Sikkerhet ikke vurdert i design-fase, manglende sikkerhetskrav, arkitektursvakheter",
        "eksisterendeBeskyttelse": "Standard utviklingsprosess",
        "eksisterendeKontroll": "Peer review",
        "K": 4,
        "I": 3,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Threat modeling i design-fase (STRIDE), security requirements, secure design patterns, defense in depth",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-005",
        "risikoelement": "Feilkonfigurasjon (Security Misconfiguration)",
        "saarbarhet": "Default credentials, unødvendige features enabled, verbose errors, manglende hardening",
        "eksisterendeBeskyttelse": "Standard konfigurasjon",
        "eksisterendeKontroll": "Deployment checklist",
        "K": 4,
        "I": 3,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Hardening guides, automated config scanning, disable debug i prod, minimal installation",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-006",
        "risikoelement": "Sårbare og utdaterte komponenter",
        "saarbarhet": "Avhengigheter med kjente CVE-er, utgått støtte, manglende oppdateringer",
        "eksisterendeBeskyttelse": "Sporadisk npm audit",
        "eksisterendeKontroll": "Manuell sjekk ved deployment",
        "K": 5,
        "I": 4,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "SCA i CI/CD (Dependabot, Snyk), inventory av komponenter, patch management policy",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-007",
        "risikoelement": "Autentiserings- og sessions-svakheter",
        "saarbarhet": "Svake passordkrav, session fixation, manglende MFA, permitterte brute force",
        "eksisterendeBeskyttelse": "Brukernavn/passord login",
        "eksisterendeKontroll": "Session cookies",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "MFA, passordløs (passkeys), rate limiting, secure session management, password policy",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-008",
        "risikoelement": "SSRF (Server-Side Request Forgery)",
        "saarbarhet": "Backend fetcher URL fra brukerinput uten validering, tilgang til interne ressurser",
        "eksisterendeBeskyttelse": "Ingen spesifikk beskyttelse",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Whitelist tillatte domener, network segmentering, disable HTTP redirects, IMDSv2",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-009",
        "risikoelement": "XSS (Cross-Site Scripting)",
        "saarbarhet": "Reflected/Stored/DOM-basert XSS, manglende output encoding",
        "eksisterendeBeskyttelse": "React auto-escaping",
        "eksisterendeKontroll": "Code review",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Output encoding, CSP headers, sanitize HTML, DOMPurify for rich text",
        "kommentarer": []
      },
      {
        "id": "baseline-webapp-010",
        "risikoelement": "CSRF (Cross-Site Request Forgery)",
        "saarbarhet": "Manglende anti-CSRF tokens, SameSite cookies ikke satt",
        "eksisterendeBeskyttelse": "Same-origin policy",
        "eksisterendeKontroll": "CORS headers",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "CSRF tokens, SameSite=Strict cookies, verify Origin/Referer headers",
        "kommentarer": []
      }
    ]
  },
  {
    "id": "baseline-database",
    "name": "Baseline - Database",
    "metadata": {
      "tjeneste": "Baseline - Database",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for databaser (SQL og NoSQL). Tilgangsstyring, kryptering, backup og compliance.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-db-001",
        "risikoelement": "Over-privilegerte database-brukere",
        "saarbarhet": "Applikasjonsbruker har DBA-rettigheter, DROP/ALTER tillatt, delte credentials",
        "eksisterendeBeskyttelse": "Separate brukere for app og admin",
        "eksisterendeKontroll": "Manuell review ved opprettelse",
        "K": 5,
        "I": 5,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "Least privilege, read-only der mulig, separate users per app, quarterly access review",
        "kommentarer": []
      },
      {
        "id": "baseline-db-002",
        "risikoelement": "Database eksponert mot internett",
        "saarbarhet": "Direkte internett-tilgang til database-port, svake credentials, default port",
        "eksisterendeBeskyttelse": "Firewall rules",
        "eksisterendeKontroll": "Network ACLs",
        "K": 5,
        "I": 5,
        "T": 5,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Private subnet/VPC, bastion host/VPN for admin, disable public access, non-standard ports",
        "kommentarer": []
      },
      {
        "id": "baseline-db-003",
        "risikoelement": "Ukryptert data at rest",
        "saarbarhet": "Database files lagret ukryptert på disk, backup ukryptert",
        "eksisterendeBeskyttelse": "Disk encryption på OS-nivå",
        "eksisterendeKontroll": "Sporadic review",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 2,
        "risikonivaa": 10,
        "foreslaatteTiltak": "TDE (Transparent Data Encryption), encrypted backups, key management (KMS/Vault)",
        "kommentarer": []
      },
      {
        "id": "baseline-db-004",
        "risikoelement": "Utilstrekkelig audit logging",
        "saarbarhet": "DDL/DML ikke logget, ingen logging av failed login attempts, manglende log retention",
        "eksisterendeBeskyttelse": "Basic query logging",
        "eksisterendeKontroll": "Logs ikke sentralisert",
        "K": 4,
        "I": 4,
        "T": 4,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Enable audit logging (DDL, DCL, failed logins), centralized logging, retention policy, SIEM integration",
        "kommentarer": []
      },
      {
        "id": "baseline-db-005",
        "risikoelement": "Manglende database backup eller untested restore",
        "saarbarhet": "Ingen backup, backup feiler, restore aldri testet, corruption i backup",
        "eksisterendeBeskyttelse": "Daglig backup til lokal disk",
        "eksisterendeKontroll": "Weekly manual check",
        "K": 5,
        "I": 5,
        "T": 5,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Automated backups, offsite/cloud backup, quarterly restore test, backup monitoring, point-in-time recovery",
        "kommentarer": []
      },
      {
        "id": "baseline-db-006",
        "risikoelement": "SQL injection via stored procedures",
        "saarbarhet": "Dynamic SQL i stored procedures, concatenation av input, manglende parameter validation",
        "eksisterendeBeskyttelse": "Stored procedures brukes",
        "eksisterendeKontroll": "Code review",
        "K": 5,
        "I": 5,
        "T": 4,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Parameterized statements i stored procedures, input validation, static code analysis",
        "kommentarer": []
      },
      {
        "id": "baseline-db-007",
        "risikoelement": "Default eller svake database credentials",
        "saarbarhet": "sa/admin/root med default passord, svake passord, ingen rotasjon",
        "eksisterendeBeskyttelse": "Passord satt ved installasjon",
        "eksisterendeKontroll": "Passord i vault",
        "K": 5,
        "I": 5,
        "T": 5,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Sterke passord, disable default accounts, password rotation, secrets manager, IAM authentication",
        "kommentarer": []
      }
    ]
  },
  {
    "id": "baseline-mobile",
    "name": "Baseline - Mobilapp",
    "metadata": {
      "tjeneste": "Baseline - Mobilapp",
      "dato": "2026-02-26",
      "beskrivelse": "Standardrisikoer for mobilapplikasjoner (iOS/Android). OWASP Mobile Top 10 og plattformspesifikke risikoer.",
      "utfortAv": "Risky"
    },
    "createdDate": "2026-02-26",
    "lastModified": "2026-02-26",
    "risikoer": [
      {
        "id": "baseline-mobile-001",
        "risikoelement": "Sensitiv data lagret usikkert på enhet",
        "saarbarhet": "API keys, tokens, passord i SharedPreferences/UserDefaults, klartekst logging",
        "eksisterendeBeskyttelse": "Data lagret lokalt",
        "eksisterendeKontroll": "Ingen spesifikk kryptering",
        "K": 5,
        "I": 4,
        "T": 2,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "Keychain (iOS), Keystore (Android), krypter sensitive data, unngå logging av secrets",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-002",
        "risikoelement": "Usikker kommunikasjon (broken cryptography)",
        "saarbarhet": "HTTP i stedet for HTTPS, certificate pinning mangler, svak TLS-config, accept any cert",
        "eksisterendeBeskyttelse": "HTTPS for prod API",
        "eksisterendeKontroll": "Standard TLS",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "Enforce HTTPS, certificate pinning, TLS 1.3, App Transport Security (iOS), Network Security Config (Android)",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-003",
        "risikoelement": "Usikker autentisering (weak authentication)",
        "saarbarhet": "Client-side auth logic, tokens lagret usikkert, manglende biometri, ingen MFA",
        "eksisterendeBeskyttelse": "Brukernavn/passord",
        "eksisterendeKontroll": "Session token",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "Server-side auth, biometric authentication, secure token storage, MFA, OAuth 2.0/OIDC",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-004",
        "risikoelement": "Usikker autorisasjon (weak authorization)",
        "saarbarhet": "Client-side authorization checks, IDOR, manglende server-side validering",
        "eksisterendeBeskyttelse": "UI-level access control",
        "eksisterendeKontroll": "Feature flags",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 4,
        "risikonivaa": 20,
        "foreslaatteTiltak": "Server-side authorization, validate all requests, RBAC/ABAC, least privilege API access",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-005",
        "risikoelement": "Utilstrekkelig input/output validering",
        "saarbarhet": "Injection-angrep via app input, XSS i WebViews, manglende sanitering",
        "eksisterendeBeskyttelse": "Basic input validation",
        "eksisterendeKontroll": "Client-side checks",
        "K": 4,
        "I": 4,
        "T": 3,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Server-side validation, parameterized queries, sanitize WebView input, CSP for WebViews",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-006",
        "risikoelement": "Reverse engineering og code tampering",
        "saarbarhet": "Ingen obfuscation, hardkoded secrets i kode, manglende root/jailbreak detection",
        "eksisterendeBeskyttelse": "Standard build",
        "eksisterendeKontroll": "Ingen spesifikk beskyttelse",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 4,
        "risikonivaa": 16,
        "foreslaatteTiltak": "Code obfuscation (ProGuard/R8, SwiftShield), root/jailbreak detection, no secrets in code, certificate pinning",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-007",
        "risikoelement": "Usikre tredjeparts-biblioteker",
        "saarbarhet": "Sårbare SDKs, over-privilegerte biblioteker, malicious packages, utdaterte avhengigheter",
        "eksisterendeBeskyttelse": "Standard npm/CocoaPods/Gradle",
        "eksisterendeKontroll": "Sporadisk oppdatering",
        "K": 5,
        "I": 4,
        "T": 3,
        "konsekvens": 5,
        "sannsynlighet": 3,
        "risikonivaa": 15,
        "foreslaatteTiltak": "SCA scanning, vet biblioteker før bruk, minimal permissions, dependency updates, SBOM",
        "kommentarer": []
      },
      {
        "id": "baseline-mobile-008",
        "risikoelement": "Exfiltrasjon via backup og logging",
        "saarbarhet": "Sensitive data i device backups, verbose logging, screenshot caching",
        "eksisterendeBeskyttelse": "Standard backup settings",
        "eksisterendeKontroll": "NSLog/Log.d brukes",
        "K": 4,
        "I": 3,
        "T": 2,
        "konsekvens": 4,
        "sannsynlighet": 3,
        "risikonivaa": 12,
        "foreslaatteTiltak": "Exclude sensitive data from backups, disable logging i prod, FLAG_SECURE for screenshots, pasteboard security",
        "kommentarer": []
      }
    ]
  }
];
window.EMBEDDED_EXAMPLE_ANALYSIS = {
  "id": "eksempel-nettbank-2026",
  "name": "ROS-analyse - Nettbank for bedriftskunder",
  "metadata": {
    "tjeneste": "Nettbank for bedriftskunder v2.0",
    "dato": "2026-02-26",
    "beskrivelse": "Risikovurdering av ny nettbankløsning for bedriftskunder med fokus på betalingsformidling, kredittgodkjenning og kontoadministrasjon. Analysen dekker både tekniske og organisatoriske risikoer.",
    "utfortAv": "Sikkerhetsteamet",
    "deltakere": "Alice Berg (sikkerhet), Bob Hansen (utvikling), Charlie Olsen (drift), Diana Larsen (compliance)",
    "tjenesteeier": "Eva Johansen - Produktansvarlig Bedriftsbank",
    "commentsSectionTitle": "TILTAK OG OPPFØLGING",
    "customTextTitle": "OPPSUMMERING OG ANBEFALINGER",
    "customText": "Denne risikoanalysen identifiserer 12 primære risikoer knyttet til den nye nettbankløsningen for bedriftskunder. Analysen viser at vi har 3 kritiske risikoer (røde) som må håndteres før produksjonssetting:\n\n1. Manglende MFA på privilegerte kontoer\n2. Utilstrekkelig logging og overvåkning av transaksjoner\n3. Ukrypterte API-kommunikasjon i utviklingsmiljø\n\nVi har også identifisert 4 høyrisikoer (oransje) som bør adresseres i løpet av Q2 2026.\n\nDe fleste risikoene kan mitigeres gjennom eksisterende sikkerhetstiltak og planlagte forbedringer. Kostnad for implementering av alle kritiske tiltak er estimert til ca. 850 000 kr over 3 måneder.\n\nAnbefaling: Utsett produksjonssetting med 6 uker for å implementere kritiske sikkerhetstiltak. Gjennomfør ny risikovurdering før go-live.",
    "acceptanceLevel": 12
  },
  "createdDate": "2026-02-26",
  "lastModified": "2026-02-26",
  "risikoer": [
    {
      "id": "risk-001",
      "nr": 1,
      "risikoelement": "Manglende MFA på privilegerte administratorkontoer",
      "saarbarhet": "Administratorkontoer i produksjon bruker kun brukernavn/passord. Ingen krav til MFA. Passwordpolicy er svak (min 8 tegn). Shared admin accounts brukes av flere.",
      "eksisterendeBeskyttelse": "VPN-tilgang påkrevd, IP-whitelisting",
      "eksisterendeKontroll": "Logging av admin-pålogging, quarterly access review",
      "K": 5,
      "I": 5,
      "T": 4,
      "konsekvens": 5,
      "sannsynlighet": 4,
      "risikonivaa": 20,
      "foreslaatteTiltak": "Implementer MFA (Yubikey/TOTP) for alle admin-kontoer. Eliminer shared accounts. Passordpolicy: min 14 tegn, complexity requirements. Periodic password rotation (90 dager).",
      "comments": [
        {
          "id": "comment-001-1",
          "type": "tiltak",
          "text": "Bestille Yubikey til alle 8 administratorer - deadline 15. mars",
          "author": "Alice Berg",
          "date": "2026-02-26",
          "visible": true
        },
        {
          "id": "comment-001-2",
          "type": "tiltak",
          "text": "Oppdatere IAM-policy for å kreve MFA på alle admin-kontoer - deadline 20. mars",
          "author": "Bob Hansen",
          "date": "2026-02-26",
          "visible": true
        },
        {
          "id": "comment-001-3",
          "type": "kommentar",
          "text": "KRITISK: Dette må være på plass før prod-setting. Compliance-krav fra Finanstilsynet.",
          "author": "Diana Larsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-002",
      "nr": 2,
      "risikoelement": "Utilstrekkelig logging og overvåkning av transaksjoner",
      "saarbarhet": "Manglende real-time overvåkning av mistenkelige transaksjoner. Logger sendes ikke til SIEM. Ingen alerting på uvanlige mønstre. Retention kun 30 dager (regulatorisk krav: 5 år).",
      "eksisterendeBeskyttelse": "Basic application logging",
      "eksisterendeKontroll": "Ukentlig manuell review av logs",
      "K": 4,
      "I": 5,
      "T": 3,
      "konsekvens": 5,
      "sannsynlighet": 4,
      "risikonivaa": 20,
      "foreslaatteTiltak": "Integrer med SIEM (Splunk). Implementer real-time fraud detection. Utvid log retention til 7 år. Alert på: transaksjoner >500k, multiple failed auth, etter-timer aktivitet.",
      "comments": [
        {
          "id": "comment-002-1",
          "type": "tiltak",
          "text": "Opprette Splunk-integrasjon - deadline 1. april",
          "author": "Charlie Olsen",
          "date": "2026-02-26",
          "visible": true
        },
        {
          "id": "comment-002-2",
          "type": "oppfolging",
          "text": "Møte med compliance for å definere eksakte logging-krav - 1. mars kl 10:00",
          "author": "Diana Larsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-003",
      "nr": 3,
      "risikoelement": "Ukryptert API-kommunikasjon i utviklingsmiljø",
      "saarbarhet": "Dev/test-miljøer bruker HTTP i stedet for HTTPS. Real production data brukes i testing. API keys hardkodet i kode. Certificates ikke validert.",
      "eksisterendeBeskyttelse": "Miljøene er på isolert VLAN",
      "eksisterendeKontroll": "Begrenset nettverkstilgang",
      "K": 5,
      "I": 4,
      "T": 2,
      "konsekvens": 5,
      "sannsynlighet": 4,
      "risikonivaa": 20,
      "foreslaatteTiltak": "Enforce HTTPS i alle miljøer. Data masking/anonymisering i dev/test. Secrets manager (Vault) for API keys. Certificate pinning.",
      "comments": [
        {
          "id": "comment-003-1",
          "type": "tiltak",
          "text": "Implementere TLS i dev/test miljøer - deadline 10. mars",
          "author": "Bob Hansen",
          "date": "2026-02-26",
          "visible": true
        },
        {
          "id": "comment-003-2",
          "type": "kommentar",
          "text": "Vi har allerede HashiCorp Vault lisens, kan gjenbruke infrastruktur",
          "author": "Charlie Olsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-004",
      "nr": 4,
      "risikoelement": "SQL injection i legacy rapporteringsmodul",
      "saarbarhet": "Gammel rapportgenerator (C# .NET Framework 4.5) bruker string concatenation i SQL queries. User input fra dato-filtre ikke sanitert.",
      "eksisterendeBeskyttelse": "Input validation på frontend (JavaScript)",
      "eksisterendeKontroll": "Read-only database user for rapporter",
      "K": 5,
      "I": 5,
      "T": 3,
      "konsekvens": 5,
      "sannsynlighet": 3,
      "risikonivaa": 15,
      "foreslaatteTiltak": "Refaktorer til parameterized queries (stored procedures). Server-side input validation. Upgrade til .NET 8. SAST scanning i CI/CD.",
      "comments": [
        {
          "id": "comment-004-1",
          "type": "tiltak",
          "text": "Skrive om rapportmodul med parameterized queries - deadline 15. april",
          "author": "Bob Hansen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-005",
      "nr": 5,
      "risikoelement": "Manglende rate limiting på API endpoints",
      "saarbarhet": "Ingen rate limiting på login, payment eller account query endpoints. Tillater brute force og credential stuffing. Kan misbrukes til DoS.",
      "eksisterendeBeskyttelse": "CloudFlare DDoS protection",
      "eksisterendeKontroll": "IP blocking ved 1000 req/min",
      "K": 3,
      "I": 3,
      "T": 5,
      "konsekvens": 4,
      "sannsynlighet": 4,
      "risikonivaa": 16,
      "foreslaatteTiltak": "Implementer rate limiting per user/IP: 5 failed logins/5min, 100 API calls/min per user, 10 payments/hour. CAPTCHA etter 3 failed attempts.",
      "comments": []
    },
    {
      "id": "risk-006",
      "nr": 6,
      "risikoelement": "Utilstrekkelig backup og disaster recovery testing",
      "saarbarhet": "Database backups kjører daglig, men restore aldri testet i prod-liknende miljø. RTO/RPO ikke definert. Backup og prod i samme AWS region. Ingen cross-region replication.",
      "eksisterendeBeskyttelse": "Daglig automated backups",
      "eksisterendeKontroll": "Backup monitoring alerts",
      "K": 4,
      "I": 5,
      "T": 5,
      "konsekvens": 5,
      "sannsynlighet": 2,
      "risikonivaa": 10,
      "foreslaatteTiltak": "Quarterly full restore test. Cross-region backup replication (eu-north-1 -> eu-west-1). Definere RTO: 4h, RPO: 1h. DR runbook og table-top exercises.",
      "comments": [
        {
          "id": "comment-006-1",
          "type": "oppfolging",
          "text": "Planlegge første restore test - 15. april",
          "author": "Charlie Olsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-007",
      "nr": 7,
      "risikoelement": "Sårbare tredjepartsbiblioteker (NPM dependencies)",
      "saarbarhet": "Frontend (React) har 47 npm packages med kjente CVEs (npm audit: 12 high, 35 moderate). Avhengigheter ikke oppdatert på 18 måneder. Ingen automated scanning.",
      "eksisterendeBeskyttelse": "Sporadisk npm audit",
      "eksisterendeKontroll": "Manual quarterly review",
      "K": 4,
      "I": 4,
      "T": 3,
      "konsekvens": 4,
      "sannsynlighet": 4,
      "risikonivaa": 16,
      "foreslaatteTiltak": "Oppdater alle dependencies. Implementer Dependabot/Snyk i GitHub. Block PRs med high/critical CVEs. Monthly dependency updates.",
      "comments": [
        {
          "id": "comment-007-1",
          "type": "tiltak",
          "text": "Kjøre npm update og teste - deadline 5. mars",
          "author": "Bob Hansen",
          "date": "2026-02-26",
          "visible": true
        },
        {
          "id": "comment-007-2",
          "type": "kommentar",
          "text": "Noen av pakkene er deprecated, må finne alternativer",
          "author": "Bob Hansen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-008",
      "nr": 8,
      "risikoelement": "Manglende segregation of duties i betalingsprosess",
      "saarbarhet": "Samme person kan initiere OG godkjenne betalinger under 100k. Ingen four-eyes principle. Audit trail eksisterer men reviewes ikke.",
      "eksisterendeBeskyttelse": "Dual approval for >100k",
      "eksisterendeKontroll": "Monthly transaction review",
      "K": 5,
      "I": 5,
      "T": 3,
      "konsekvens": 5,
      "sannsynlighet": 2,
      "risikonivaa": 10,
      "foreslaatteTiltak": "Implementer maker-checker for alle betalinger >25k. Separate roller: initiator, approver, releaser. Weekly audit trail review med anomaly detection.",
      "comments": []
    },
    {
      "id": "risk-009",
      "nr": 9,
      "risikoelement": "GDPR - utilstrekkelig data sletting ved kundeoppgjør",
      "saarbarhet": "Når bedriftskunde avslutter forhold, slettes ikke persondata automatisk. Data ligger i backups i 90 dager. Manglende prosess for 'right to be forgotten'. Soft deletes brukes (data flagges, ikke slettet).",
      "eksisterendeBeskyttelse": "Manual sletting ved forespørsel",
      "eksisterendeKontroll": "Legal review av datahåndtering",
      "K": 4,
      "I": 4,
      "T": 2,
      "konsekvens": 4,
      "sannsynlighet": 3,
      "risikonivaa": 12,
      "foreslaatteTiltak": "Automated data retention policy (delete etter 30 dager post-avslutning, 7 års retention for transaksjonsdata pga regulatoriske krav). Hard deletes fra prod, separate compliance archive.",
      "comments": [
        {
          "id": "comment-009-1",
          "type": "oppfolging",
          "text": "Avklare med juridisk hva som er regulatoriske krav vs GDPR - 28. februar",
          "author": "Diana Larsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-010",
      "nr": 10,
      "risikoelement": "Insider threat - overpriviligerte database-tilganger",
      "saarbarhet": "15 utviklere har GRANT ALL på prod database. DBAs har ukontrollert tilgang til krypteringsnøkler. Ingen logging av admin queries. Separation prod/non-prod ikke håndhevet.",
      "eksisterendeBeskyttelse": "VPN + MFA for database access",
      "eksisterendeKontroll": "Annual access review",
      "K": 5,
      "I": 5,
      "T": 3,
      "konsekvens": 5,
      "sannsynlighet": 2,
      "risikonivaa": 10,
      "foreslaatteTiltak": "Least privilege: utviklere kun SELECT på prod views. Admin access via bastion/jump server med session recording. Key management: split-knowledge, M-of-N encryption. Quarterly access reviews.",
      "comments": [
        {
          "id": "comment-010-1",
          "type": "tiltak",
          "text": "Revoke GRANT ALL fra utviklere, gi read-only views - deadline 20. mars",
          "author": "Charlie Olsen",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    },
    {
      "id": "risk-011",
      "nr": 11,
      "risikoelement": "Manglende sikkerhetstrening for utviklere",
      "saarbarhet": "Utviklere har ikke gjennomført secure coding training. Ingen awareness om OWASP Top 10. Code review fokuserer på funksjonalitet, ikke sikkerhet. Threat modeling ikke del av SDLC.",
      "eksisterendeBeskyttelse": "Generell onboarding training",
      "eksisterendeKontroll": "Annual general security awareness",
      "K": 3,
      "I": 3,
      "T": 2,
      "konsekvens": 3,
      "sannsynlighet": 4,
      "risikonivaa": 12,
      "foreslaatteTiltak": "Mandatory secure coding training (SANS/OWASP). Quarterly threat modeling workshops. Security champion program. Integrate security into code review checklist.",
      "comments": []
    },
    {
      "id": "risk-012",
      "nr": 12,
      "risikoelement": "Utilstrekkelig incident response plan",
      "saarbarhet": "Ingen dokumentert IR plan for security incidents. Kontaktlister utdatert. Ingen defined escalation paths. IR team aldri testet (table-top eller simulations). Mean time to detect (MTTD) ukjent.",
      "eksisterendeBeskyttelse": "Generell IT incident prosess",
      "eksisterendeKontroll": "24/7 NOC monitoring",
      "K": 3,
      "I": 3,
      "T": 4,
      "konsekvens": 4,
      "sannsynlighet": 3,
      "risikonivaa": 12,
      "foreslaatteTiltak": "Utvikle IR playbooks (ransomware, data breach, insider threat, DDoS). Bi-annual tabletop exercises. Define SLAs: MTTD <15min, MTTR <4h. Integrate med ekstern IR vendor (retainer agreement).",
      "comments": [
        {
          "id": "comment-012-1",
          "type": "oppfolging",
          "text": "Planlegge første tabletop exercise i Q2 - tema: ransomware scenario",
          "author": "Alice Berg",
          "date": "2026-02-26",
          "visible": true
        }
      ]
    }
  ]
};
